CREATE TABLE PRODUCT(
	PRODUCT_ID INT IDENTITY PRIMARY KEY,
	PRODUCT_CODE VARCHAR(10) NOT NULL,
	PRODUCT_NAME NVARCHAR(50) NOT NULL,
	PRODUCT_TYPE int NOT NULL,
	PRODUCT_URL NVARCHAR(50) NOT NULL,
	PRODUCT_PRICE INT NOT NULL,
	PRODUCT_QUANTITY INT,
	PRODUCT_DESCRIPTION NVARCHAR(255),
	
	PRODUCT_STATUS INT NOT NULL,
)
GO
CREATE TABLE BOOK(
	BOOK_ID INT IDENTITY PRIMARY KEY,
	BOOK_CODE VARCHAR(10) NOT NULL,
	BOOK_NAME NVARCHAR(50) NOT NULL,
	BOOK_DESCRIPTION NVARCHAR(255),
	BOOK_COUPON VARCHAR(10),
	BOOK_STARTDAY DATETIME ,
	BOOK_QUANTITY INT NOT NULL,
	BOOK_PRODUCT INT,
	BOOK_QUANTITY_PRODUCT INT,
	
	BOOK_USER INT NOT NULL,
	BOOK_STATUS INT NOT NULL, 
	CONSTRAINT FK_BOOK_USERS FOREIGN KEY (BOOK_USER) REFERENCES USERS(USERS_ID),
	CONSTRAINT FK_BOOK_PRODUCT FOREIGN KEY (BOOK_PRODUCT) REFERENCES PRODUCT(PRODUCT_ID),

	)

	GO
	CREATE TABLE BILL(
	BILL_ID INT IDENTITY PRIMARY KEY,
	BILL_CODE VARCHAR(10) NOT NULL,
	BILL_NAME NVARCHAR(50) NOT NULL,
	BILL_ADDRESS_ORDER NVARCHAR(100),
	BILL_DAY_PRINT DATE NOT NULL,
	BILL_TOTAL INT NOT NULL,
	BILL_DESCRIPTION NVARCHAR(255),
	BILL_STATUS INT NOT NULL,
	BILL_BOOK INT NOT NULL,
	CONSTRAINT FK_BILL_BOOK FOREIGN KEY (BILL_BOOK) REFERENCES BOOK(BOOK_ID),
	
	)

	GO
	DROP TABLE BILL

CREATE TABLE USERS(
	USERS_ID INT IDENTITY PRIMARY KEY,
	USER_CODE VARCHAR(10) NOT NULL,
	USERS_NAME NVARCHAR(50) NOT NULL,
	USER_DATEOFBIRTH DATE,
	USER_PHONE VARCHAR(10),
	USER_ADDRESS NVARCHAR(60),
	USER_STATUS INT NOT NULL,
	USERS_DESCRIPTION NVARCHAR(255),
	USER_BANK_ACCOUNT VARCHAR(20),
	USER_BANK_NAME NVARCHAR(30),
	USER_NOTIFICATION INT,	
	CONSTRAINT FK_USER_NOTIFICATION FOREIGN KEY (USER_NOTIFICATION) REFERENCES NOTIFICATIONS(NOTIFI_ID),
	)
GO

CREATE TABLE ROLE(
	ROLE_ID INT IDENTITY PRIMARY KEY,
	ROLE_CODE VARCHAR(10) NOT NULL,
	ROLE_NAME NVARCHAR(50) NOT NULL,
	ROLE_DESCRIPTION NVARCHAR(255),
	ROLE_STATUS INT,
	ROLE_USER INT,
	CONSTRAINT FK_ROLE_USER FOREIGN KEY (ROLE_USER) REFERENCES USERS(USERS_ID),
	
)
GO
CREATE TABLE NOTIFICATIONS (
	NOTIFI_ID INT IDENTITY PRIMARY KEY,
	NOTIFI_CODE VARCHAR(10) NOT NULL,
	NOTIFI_NAME NVARCHAR(50),
	NOTIFI_DESCRIPTION NVARCHAR(255),
	NOTIFI_STATUS INT,
)
GO
select * from NOTIFICATIONS
CREATE TABLE ACCOUNT(
ACCOUNT_ID INT IDENTITY PRIMARY KEY,
USERS_ID INT FOREIGN KEY (USERS_ID) REFERENCES USERS(USERS_ID),
USERNAME VARCHAR(10) not null,
PASSWORD VARCHAR(50) NOT NULL
)
GO